config:
  line-length: false # MD013 – disable line length limits
  no-inline-html: false # MD033 – allow inline HTML

globs:
  - "**/*.md"
  - "!node_modules"
  - "!**/node_modules"
  - "!ui/node_modules/**"
  - "!ui/dist/**"
  - "!target"
  - "!**/target"
